## PyTorch - Tensors

#### What are Tensors?

Tensors are specialized data structures that are very similar to arrays and matrices. They are the fundamental building blocks in PyTorch (and other deep learning frameworks).

Tensors are like NumPy's `ndarrays`, but with additional capabilities, such as:
- Running on GPUs for acceleration
- Supporting automatic differentiation (crucial for training neural networks)

They are used for storing and operating on numerical data and can have any number of dimensions.

| Tensor Type | Description | Example |
| --- | --- | --- |
| 0-D Tensor | Scalar | torch.tensor(5) |
| 1-D Tensor | Vector | torch.tensor([1, 2, 3]) |
| 2-D Tensor | Matrix | torch.tensor([[1, 2], [3, 4]]) |
| 3-D+ Tensor | Multi-dimensional array / Tensor | torch.rand(3, 3, 3) |

#### Creating a Tensor

In [1]:
import torch
import numpy as np

# Allocate memory for the tensor
tensor_empty = torch.empty(3, 4)

# Directly from data
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)
print(tensor_data)

# From a NumPy array
np_array = np.array(data)
tensor_numpy = torch.from_numpy(np_array)
print(tensor_numpy)

# Initialize tensor with all zeros/ones
tensor_zeros = torch.zeros(2, 3)
tensor_ones = torch.ones(2, 3)
print(tensor_zeros)
print(tensor_ones)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### Creating Tensors with Random Values

In [2]:
# torch.manual_seed(123) # For creating a seed

# Uniform distribution, range is [0, 1)
# Output type is float
tensor_random1 = torch.rand(2, 3)
print(tensor_random1)

# Normal (Gaussian) distribution, with mean = 0 and standard deviation = 1
# Range is theoretically infinite, but usually around -3 to 3
# Output type is float
tensor_random2 = torch.randn(2, 3)
print(tensor_random2)

# Uniform distribution over integers
# Range can be speficied with low and high 
# Output type is integer
tensor_random3 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor_random3)

tensor([[0.8941, 0.3848, 0.3506],
        [0.3186, 0.7266, 0.6338]])
tensor([[-0.1142,  1.1888,  0.2506],
        [-0.5719,  2.9942, -0.7190]])
tensor([[2, 3, 7],
        [7, 5, 5]])


Functions like `torch.zeros_like()`, `torch.ones_like()`, `torch.rand_like()`, `torch.randn_like()` and `torch.randint_like()` are used to create new tensors with the same shape and type as an existing tensor.

#### Numpy Bridge

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
- Tensor to NumPy array: `numpy_array = tensor.numpy()`
- NumPy array to Tensor: `tensor = torch.from_numpy(numpy_array)`

#### Attributes of a Tensor

In [3]:
tensor = torch.rand(3, 4)

print(type(tensor))
print(f"Shape of tensor: {tensor.shape}")
print(f"Number of dimensions: {tensor.ndim}")
print(f"Data type of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Total number of elements: {tensor.numel()}")


<class 'torch.Tensor'>
Shape of tensor: torch.Size([3, 4])
Number of dimensions: 2
Data type of tensor: torch.float32
Device tensor is stored on: cpu
Total number of elements: 12


#### Tensor Datatypes

The default `dtype` of `torch.Tensor` is `torch.float32` (also known as `torch.FloatTensor`, a 32-bit floating point).

For backwards compatibility, PyTorch provides specific CPU and GPU class names for some data types, though using `dtype=torch.*` is recommended.

There are also 32/64/128-bit complex data types, as well as 16/32/64-bit integer (unsigned) data types.

| Data Type | Description | CPU Tensor Class | GPU Tensor Class |
| --- | --- | --- | --- |
| torch.float16 | 16-bit floating point | torch.HalfTensor | torch.cuda.HalfTensor |
| torch.bfloat16 | 16-bit floating point | torch.BFloat16Tensor | torch.cuda.BFloat16Tensor |
| torch.float32 / torch.float | 32-bit floating point | torch.FloatTensor | torch.cuda.FloatTensor |
| torch.float64 / torch.double | 64-bit floating point | torch.DoubleTensor | torch.cuda.DoubleTensor |
| torch.uint8 | 8-bit integer (unsigned) | torch.ByteTensor | torch.cuda.ByteTensor |
| torch.int8 | 8-bit integer (signed) | torch.CharTensor | torch.cuda.CharTensor |
| torch.int16 / torch.short | 16-bit integer (signed) | torch.ShortTensor | torch.cuda.ShortTensor |
| torch.int32 / torch.int | 32-bit integer (signed) | torch.IntTensor | torch.cuda.IntTensor |
| torch.int64 / torch.long | 64-bit integer (signed) | torch.LongTensor | torch.cuda.LongTensor |
| torch.bool | Boolean | torch.BoolTensor | torch.cuda.BoolTensor |

The `.to()` method is used to move a tensor to a specific device (CPU or GPU), change the data type of a tensor or both at the same time.

In [4]:
tensor1 = torch.tensor([1.0, 2.0])
tensor_gpu = tensor1.to("cuda") # Moves tensor to GPU (if available)
tensor_cpu = tensor_gpu.to("cpu") # Moves tensor back to CPU
tensor_int = tensor1.to(torch.int32)
tensor_new = tensor1.to(dtype=torch.float64, device="cuda")

#### Tensor Operations

Tensor operations refer to the wide range of functions and methods that can be applied to `torch.Tensor` objects.

- Refer to: https://pytorch.org/docs/stable/tensors.html

In [5]:
# Count the number of attributes/functions/classes in the torch module
print("torch module:", len(dir(torch)))

# Count the number of attributes/methods in torch.Tensor class
print("torch.tensor class:", len(dir(torch.Tensor)))

torch module: 1451
torch.tensor class: 749


In [6]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Using a trailing underscore '_' for in-place ops:
a1 = torch.tensor([1.0, 2.0, 3.0])
print("a after add_:\n", a1.add_(1))
print("a after mul_:\n", a1.mul_(2))

# Dot Product
print("Dot product:\n", torch.dot(a, b))

# Matrix Multiplication, shorthand @
c1 = torch.matmul(a, b) # a @ b
print("Matrix mul:\n", c1)

# Element Multiplication
c2 = torch.mul(a, b) # a * b
print("Element mul:\n", c2)

# Concatenation
# Join tensors along an existing dimension
d = torch.cat((a, b), dim=0)
print("Concatenated:\n", d)

# Stacking
# Adds a new dimension
e = torch.stack((a, b), dim=0)
print("Stacked:\n", e)

# Reshape
f = torch.arange(12) # shape (12,)
print("View (3x4):\n", f.view(3, 4))
print("Reshape (3x4):\n", f.reshape(3, 4))

# Transpose
g = torch.randn(2, 2)
print("Original g:\n", g)
print("Transposed g:\n", g.T)

# Cloning, important to avoid unwanted sharing
h1 = g.clone()

# Detach, used in autograd to stop gradients
h2 = g.detach()

# Fill, making a tensor with the provided value
i = torch.full((3, 4), 5.0)
print("Filled with 5:\n", i)

# Diagonal matrix
j1 = torch.tensor([1, 2, 3])
print("Diagonal:\n", torch.diag(j1))

# Eye matrix
j2 = torch.eye(3)
print("Eye:\n", j2)

# Conditionally selecting elements
k = torch.tensor([1, 2, 3, 4, 5, 6, 7])
k1 = torch.where(k > 3, k, -1)
print(k1)

a after add_:
 tensor([2., 3., 4.])
a after mul_:
 tensor([4., 6., 8.])
Dot product:
 tensor(32.)
Matrix mul:
 tensor(32.)
Element mul:
 tensor([ 4., 10., 18.])
Concatenated:
 tensor([1., 2., 3., 4., 5., 6.])
Stacked:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
View (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Reshape (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Original g:
 tensor([[-0.7772,  0.5842],
        [ 2.3193, -0.6538]])
Transposed g:
 tensor([[-0.7772,  2.3193],
        [ 0.5842, -0.6538]])
Filled with 5:
 tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])
Diagonal:
 tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
Eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([-1, -1, -1,  4,  5,  6,  7])


#### Changing the Number of Dimensions

In [7]:
tensor_a = torch.rand(3, 256, 256)
tensor_b = tensor_a.unsqueeze(0)

print("tensor_a:", tensor_a.shape)
print("tensor_b:", tensor_b.shape)

tensor_c = torch.rand(1, 5)
tensor_d = tensor_c.squeeze(0)

print("tensor_c:", tensor_c)
print("tensor_d:", tensor_d)

tensor_a: torch.Size([3, 256, 256])
tensor_b: torch.Size([1, 3, 256, 256])
tensor_c: tensor([[0.2834, 0.2805, 0.3908, 0.6951, 0.3021]])
tensor_d: tensor([0.2834, 0.2805, 0.3908, 0.6951, 0.3021])


#### Saving and Loading Tensors

In [8]:
s_tensor = torch.tensor([1, 2, 3, 4, 5])
# torch.save(s_tensor, "file_name.txt")

# l_tensor = torch.load("file_name.txt")