## PyTorch - Tensors

##### What are Tensors?

Tensors are specialized data structures that are very similar to arrays and matrices. They are the fundamental building blocks in PyTorch (and other deep learning frameworks).

Tensors are like NumPy's `ndarrays`, but with additional capabilities, such as:
- Running on GPUs for acceleration
- Supporting automatic differentiation (crucial for training neural networks)

They are used for storing and operating on numerical data and can have any number of dimensions.

| Tensor Type | Description | Example |
| --- | --- | --- |
| 0-D Tensor | Scalar | torch.tensor(5) |
| 1-D Tensor | Vector | torch.tensor([1, 2, 3]) |
| 2-D Tensor | Matrix | torch.tensor([[1, 2], [3, 4]]) |
| 3-D+ Tensor | Multi-dimensional array / Tensor | torch.rand(3, 3, 3) |

##### Creating a Tensor

In [1]:
import torch
import numpy as np

# Allocate memory for the tensor
tensor_empty = torch.empty(3, 4)

# Directly from data
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)
print(tensor_data)

# From a NumPy array
np_array = np.array(data)
tensor_numpy = torch.from_numpy(np_array)
print(tensor_numpy)

# Initialize tensor with all zeros/ones
tensor_zeros = torch.zeros(2, 3)
tensor_ones = torch.ones(2, 3)
print(tensor_zeros)
print(tensor_ones)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


##### Creating a Tensors Randomly

In [2]:
# torch.manual_seed(123) # For creating a seed

# Uniform distribution, range is [0, 1)
# Output type is float
tensor_random1 = torch.rand(2, 3)
print(tensor_random1)

# Normal (Gaussian) distribution, with mean = 0 and standard deviation = 1
# Range is theoretically infinite, but usually around -3 to 3
# Output type is float
tensor_random2 = torch.randn(2, 3)
print(tensor_random2)

# Uniform distribution over integers
# Range can be speficied with low and high 
# Output type is integer
tensor_random3 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor_random3)

tensor([[0.4196, 0.4937, 0.6442],
        [0.0257, 0.7535, 0.2406]])
tensor([[-0.2395, -1.6617,  0.4688],
        [-1.1625, -1.8545,  1.6762]])
tensor([[5, 4, 4],
        [9, 0, 0]])


Functions like `torch.zeros_like()`, `torch.ones_like()`, `torch.rand_like()`, `torch.randn_like()` and `torch.randint_like()` are used to create new tensors with the same shape and type as an existing tensor.

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
- Tensor to NumPy array: `numpy_array = tensor.numpy()`
- NumPy array to Tensor: `tensor = torch.from_numpy(numpy_array)`

##### Attributes of a Tensor

In [3]:
tensor = torch.rand(3, 4)

print(type(tensor))
print(f"Shape of tensor: {tensor.shape}")
print(f"Number of dimensions: {tensor.ndim}")
print(f"Data type of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Total number of elements: {tensor.numel()}")


<class 'torch.Tensor'>
Shape of tensor: torch.Size([3, 4])
Number of dimensions: 2
Data type of tensor: torch.float32
Device tensor is stored on: cpu
Total number of elements: 12


##### Tensor Datatypes

The default `dtype` of `torch.Tensor` is `torch.float32` (also known as `torch.FloatTensor`, a 32-bit floating point).

For backwards compatibility, PyTorch provides specific CPU and GPU class names for some data types, though using `dtype=torch.*` is recommended.

There are also 32/64/128-bit complex data types, as well as 16/32/64-bit integer (unsigned) data types.

| Data Type | Description | CPU Tensor Class | GPU Tensor Class |
| --- | --- | --- | --- |
| torch.float16 | 16-bit floating point | torch.HalfTensor | torch.cuda.HalfTensor |
| torch.bfloat16 | 16-bit floating point | torch.BFloat16Tensor | torch.cuda.BFloat16Tensor |
| torch.float32 / torch.float | 32-bit floating point | torch.FloatTensor | torch.cuda.FloatTensor |
| torch.float64 / torch.double | 64-bit floating point | torch.DoubleTensor | torch.cuda.DoubleTensor |
| torch.uint8 | 8-bit integer (unsigned) | torch.ByteTensor | torch.cuda.ByteTensor |
| torch.int8 | 8-bit integer (signed) | torch.CharTensor | torch.cuda.CharTensor |
| torch.int16 / torch.short | 16-bit integer (signed) | torch.ShortTensor | torch.cuda.ShortTensor |
| torch.int32 / torch.int | 32-bit integer (signed) | torch.IntTensor | torch.cuda.IntTensor |
| torch.int64 / torch.long | 64-bit integer (signed) | torch.LongTensor | torch.cuda.LongTensor |
| torch.bool | Boolean | torch.BoolTensor | torch.cuda.BoolTensor |

The `.to()` method is used to move a tensor to a specific device (CPU or GPU), change the data type of a tensor or both at the same time.

In [4]:
tensor1 = torch.tensor([1.0, 2.0])
tensor_gpu = tensor1.to("cuda") # Moves tensor to GPU (if available)
tensor_cpu = tensor_gpu.to("cpu") # Moves tensor back to CPU
tensor_int = tensor1.to(torch.int32)
tensor_new = tensor1.to(dtype=torch.float64, device="cuda")

##### Tensor Operations

There are more than 1200 tensor operations. Refer to: https://pytorch.org/docs/stable/tensors.html

In [5]:
# Count the attributes in torch
print(len(dir(torch)))

# Count only tensor methods
print(len(dir(torch.Tensor))) 

1451
749


In [6]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Using a trailing underscore '_' for in-place ops:
print("a after add_:\n", a.add_(1))
print("a after mul_:\n", a.mul_(2))

# Matrix Multiplication, shorthand @
c = torch.matmul(a , b) # a @ b
print("Dot product:\n", c)

# Concatenation
# Join tensors along an existing dimension
d = torch.cat((a, b), dim=0)
print("Concatenated:\n", d)

# Stacking
# Adds a new dimension
e = torch.stack((a, b), dim=0)
print("Stacked:\n", e)

# Reshape
f = torch.arange(12) # shape (12,)
print("View (3x4):\n", f.view(3, 4))
print("Reshape (3x4):\n", f.reshape(3, 4))

# Transpose
g = torch.randn(2, 2)
print("Original g:\n", g)
print("Transposed g:\n", g.T)

# Cloning, important to avoid unwanted sharing
h1 = g.clone()

# Detach, used in autograd to stop gradients
h2 = g.detach()

# Fill, making a tensor with the provided value
i = torch.full((3, 4), 5.0)
print("Filled with 5:\n", i)

# Diagonal matrix
j1 = torch.tensor([1, 2, 3])
print("Diagonal:\n", torch.diag(j1))

# Eye matrix
j2 = torch.eye(3)
print("Eye:\n", j2)

a after add_:
 tensor([2., 3., 4.])
a after mul_:
 tensor([4., 6., 8.])
Dot product:
 tensor(94.)
Concatenated:
 tensor([4., 6., 8., 4., 5., 6.])
Stacked:
 tensor([[4., 6., 8.],
        [4., 5., 6.]])
View (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Reshape (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Original g:
 tensor([[ 1.4298,  1.8391],
        [-0.3723,  0.3940]])
Transposed g:
 tensor([[ 1.4298, -0.3723],
        [ 1.8391,  0.3940]])
Filled with 5:
 tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])
Diagonal:
 tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
Eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
